name: Container Image CI

on:
   workflow_dispatch:

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Docker Image
        run: docker build -t ghcr.io/mikecayan99/secure-azure-container-platform:${{ github.sha }} ./app
