name: Container Image CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/container-ci.yml"
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/container-ci.yml"

jobs:

  build-test:

    permissions:
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ghcr.io/mikecayan99/secure-azure-container-platform
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./app
          load: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Docker Image 
        run: docker run -d --name secure-platform-test -p 127.0.0.1:8080:8080 ghcr.io/mikecayan99/secure-azure-container-platform:${{ steps.meta.outputs.version }}

      - name: Check container status
        run: docker ps -a

      - name: show container logs
        run: docker logs secure-platform-test

      - name: Test Docker Image
        run: |
          curl \
            --fail \
            --retry 10 \
            --retry-delay 5 \
            --retry-all-errors \
            http://127.0.0.1:8080/health

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'ghcr.io/mikecayan99/secure-azure-container-platform:${{ steps.meta.outputs.version }}'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          ignore-unfixed: true
          severity: 'CRITICAL'

  publish:
    needs: build-test

    if: ${{ github.event_name == 'push' }}

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ghcr.io/mikecayan99/secure-azure-container-platform
          tags: |
            type=ref,event=branch
            type=sha

      - name: Log in to GHCR
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
