name: Container Image CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mikecayan99/secure-azure-container-platform
          tags: |
            type=ref,event=branch
            type=sha

      - name: Show Docker metadata tags
        run: echo "${{ steps.meta.outputs.tags }}"

      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./app
          load: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Docker Image 
        run: docker run -d --name secure-platform-test -p 127.0.0.1:8080:8080 ghcr.io/mikecayan99/secure-azure-container-platform:${{ github.sha }}

      - name: Check container status
        run: docker ps -a

      - name: show container logs
        run: docker logs secure-platform-test

      - name: Test Docker Image
        run: |
          curl \
            --fail \
            --retry 10 \
            --retry-delay 5 \
            --retry-all-errors \
            http://127.0.0.1:8080/health

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'ghcr.io/mikecayan99/secure-azure-container-platform:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


      - name: Log in to GHCR
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GHCR
        if: ${{ github.event_name == 'push' }}
        run: docker push ghcr.io/mikecayan99/secure-azure-container-platform:${{ github.sha }}
